# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


KMER_RANGE = range(config["kmer_start"], config["kmer_end"] + 1)
RUN_NAME = config["name"]


# load rules
# -----------------------------------------------------
include: "rules/utility.smk"
include: "rules/simulate_genom.smk"
include: "rules/read_mapping.smk"
include: "rules/kmer_count.smk"
include: "rules/generate_reads.smk"

# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


def check_error_file():
    import os
    import datetime
    error_file = "error_current_run.txt"
    now = datetime.datetime.now()
    if not os.path.isfile(error_file):
        with open(error_file, "w") as f:
            f.write("\n--- An error occurred! ---\n")
    return error_file, time_stamp


onerror:
    error_file, now = check_error_file()
    try:
        with open(error_file, "a") as f:
            f.write(f"\n\n\n{time_stamp}\n")
            f.write(str(failed_jobs))
    finally:
        print("error recorded")
    #     # Trigger your custom action (e.g., a bash script)
    #     shell(f"bash cleanup_script.sh --in {inputs} --out {outputs}")


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        expand([
            f"results/plots/benchmark_markov_{RUN_NAME}_{{kmer}}kmer_plot.tsv",
            f"results/plots/kmer_{RUN_NAME}_{{kmer}}.tsv",
            f"results/plots/kmer_{RUN_NAME}_{{kmer}}_intersect0.tsv",
            f"results/plots/kmer_{RUN_NAME}_{{kmer}}_intersect1.tsv",
            ],
            kmer=KMER_RANGE),
